### ISSUE TITLE
[Bug] BLE Client connection failure decreases connected count errorneously

### ISSUE THREAD

**Issue by jhfoo** [bettr-xyz/tracesigma-firmware#26]
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fespressif%2Farduino-esp32%2Fissues%2F3974&sa=D&sntz=1&usg=AFQjCNG-9EODWuzWYTsUgQl1KFPqJ0rWug

**Comment by jamesi8086** [comment]
solved in BLE library patch. patch PR sent to espressif.
