### ISSUE TITLE
[UX] As a user, I need to know if the device is connecting or connected to wifi

### ISSUE THREAD

**Issue by jamesi8086** [bettr-xyz/tracesigma-firmware#55]
An icon on main screen should show wifi connection states

**Comment by zhenwei2972** [comment]
will work on this!

**Comment by jamesi8086** [comment]
Thanks, there are some UI mockups here:

https://docs.google.com/presentation/d/1XhkHZvV406Z9BaXHTgYoJRKf80tuK4oX42cNboWrHcI/edit?usp=sharing

**Comment by jamesi8086** [comment]
coord with @fustilio for more info on how to interact with our task and state machines to propagate the info to the frontend

**Comment by jhfoo** [comment]
Close on duplicate.
