### ISSUE TITLE
[UX] As a user, I want to see battery % or if it is charging

### ISSUE THREAD

**Issue by jamesi8086** [bettr-xyz/tracesigma-firmware#59]
We need some icons to display the battery/charge state on the UI

https://docs.google.com/presentation/d/1XhkHZvV406Z9BaXHTgYoJRKf80tuK4oX42cNboWrHcI/edit?usp=sharing

**Comment by fustilio** [comment]
I think both of these are done already. Maybe can improve the battery % accuracy by using the non deprecated function...

**Comment by jamesi8086** [comment]
we can try to have some icons so that it does not take up too much space on the display

**Comment by jamesi8086** [comment]
follow Android/iOS

**Comment by jamesi8086** [comment]
Created some mockups on how we could improve the visuals:

https://docs.google.com/presentation/d/1XhkHZvV406Z9BaXHTgYoJRKf80tuK4oX42cNboWrHcI/edit?usp=sharing

**Comment by fustilio** [comment]
Added battery icons in #83
